services:

    postgres:
      image: postgres
      container_name: referral_db
      env_file:
        - .env
      environment:
        DATABASE_URL: ${DATABASE_URL}
      ports:
        - "5432:5432"
      volumes:
        - referral_db_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 5s
        timeout: 5s
        retries: 5
  
    app:
      image: referral_app
      container_name: referral_app
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      env_file:
        - .env
      ports:
        - "8000:8000"
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      postgres:
        condition: service_healthy

    alembic:
      image: referral_app
      container_name: alembic
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - .env
      command:
        alembic upgrade head
      depends_on:
        postgres:
          condition: service_healthy
        redis:
          condition: service_healthy

    redis:
      image: redis
      container_name: referral_redis
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 5s
        timeout: 3s
        retries: 5

volumes:
  redis_data:
  referral_db_data:
