"""owner has many refcodes

Revision ID: e87e49ad0de2
Revises: e70536cd1f09
Create Date: 2025-03-10 14:50:39.550147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e87e49ad0de2'
down_revision: Union[str, None] = 'e70536cd1f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('referral_codes_owner_id_key', 'referral_codes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('referral_codes_owner_id_key', 'referral_codes', ['owner_id'])
    # ### end Alembic commands ###
